### ISSUE TITLE
opam package `available:` field

### ISSUE THREAD

**Issue by AltGr** [toolslive/ordma#5]
The provided opam file specifies:

```
available: [ os != "darwin" | ocaml-version >= "4.02.0" ]
```

which means that on e.g. Linux any OCaml version is supported. I just wanted to know if this is an error or if there is a reason to it ?
(I am currently performing automated rewrites on the opam repository, and this is more difficult to translate than the usual case -- a conjunction rather than a disjunction --, so I am interested to know if there is a real use for it)
Thanks!

**Comment by toolslive** [comment]
That's a mistake : It should have been : 
`available: [os = "linux" & ocaml-version >= "4.02.0"]`
as was the case in [version 0.0.1](https://github.com/ocaml/opam-repository/blob/master/packages/ordma/ordma.0.0.1/opam#L18)

I'll adapt

**Comment by AltGr** [comment]
Great, that'll make it easier for me ;)

**Comment by toolslive** [comment]
see: 
https://github.com/toolslive/ordma/commit/2d4722e6a40199b404cd94f4f4be7958d17a20e6

I guess you want me to release a new version into opam ?

**Comment by AltGr** [comment]
Fixing the existing opam file in the opam-repository is fine, as this is just a metadata fix. I'll file a PR for the change.
